<?php

namespace AdminBundle\Repository;

/**
 * ArtistsgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistsgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
